CREATE SEQUENCE seq_coordinates_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_location_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_person_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_movie_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_mpaa_rating_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_color_id START WITH 1 INCREMENT BY 1;